include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

linter:
  rules:
    # Disable for icon classes that use snake_case naming convention
    constant_identifier_names: false
